"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import atexit

from decouple import Config, RepositoryEnv

# Import custom SSH tunnel implementation instead of sshtunnel
from core.ssh_tunnel import ParametrikoSSHTunnel

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOTENV_FILE = os.environ.get("DOTENV_FILE", "dev.env")
env_config = Config(RepositoryEnv(DOTENV_FILE))
# Check os.environ first for ENVIRONMENT (important for tests)
ENVIRONMENT = os.environ.get("ENVIRONMENT") or env_config.get(
    "ENVIRONMENT", default="local"
)
PROD_ENVIRONMENTS = ["prod", "production"]

# Print environment info on startup
print(f"[SETTINGS] ENVIRONMENT: {ENVIRONMENT}")
print(f"[SETTINGS] DOTENV_FILE: {DOTENV_FILE}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c@n!z)na@3h_^@xp^3bfi7gqk!*gtlk@!1_ud7e2y8lv1q5ddx"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config.get("DEBUG") == "TRUE"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django rest framework
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    # filters
    "django_filters",
    # celery
    "django_celery_results",
    "django_celery_beat",
    # custom apps
    "parameters",
    "apps.wallets",
    "apps.yields",
    "apps.positions",
    "apps.agent",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django_samesite_none.middleware.SameSiteNoneMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration - environment-based selection
# When USE_DEFAULT_DB is False, use SQLite for testing (fast and no dependencies)
USE_DEFAULT_DB = env_config.get("USE_DEFAULT_DB", default="TRUE") == "TRUE"

if not USE_DEFAULT_DB:
    # SQLite configuration for testing
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    USE_SSH_TUNNEL = env_config.get("USE_SSH_TUNNEL") == "TRUE"

    if USE_SSH_TUNNEL:
        # Configure SSH Tunnel with our custom implementation
        ssh_tunnel = ParametrikoSSHTunnel(
            ssh_address_or_host=(
                env_config.get("BASTION_HOST"),
                int(env_config.get("BASTION_PORT")),
            ),  # Address of the bastion
            ssh_username=env_config.get(
                "BASTION_USERNAME"
            ),  # SSH username for the bastion
            ssh_pkey=env_config.get("BASTION_KEY_PATH"),
            remote_bind_address=(
                env_config.get("DB_ENDPOINT"),
                5432,
            ),  # Remote RDS host and port
            local_bind_address=("127.0.0.1", 0),  # Localhost and random port
            keepalive_interval=60,  # Send keepalive every minute
        )
        ssh_tunnel.start()

        # Register cleanup function to ensure tunnel is closed on exit
        atexit.register(ssh_tunnel.stop)

        # Update DATABASES to use the tunnel
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env_config.get("DB_NAME"),
                "USER": env_config.get("DB_USERNAME"),
                "PASSWORD": env_config.get("DB_PASS"),
                "HOST": ssh_tunnel.local_bind_host,  # Tunnel host
                "PORT": ssh_tunnel.local_bind_port,  # Port allocated by the tunnel
            }
        }
    else:
        # Direct connection (e.g., in production)
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env_config.get("DB_NAME"),
                "USER": env_config.get("DB_USERNAME"),
                "PASSWORD": env_config.get("DB_PASS"),
                "HOST": env_config.get("DB_ENDPOINT"),
                "PORT": 5432,
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# AWS_ACCESS_KEY_ID = env_config.get("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = env_config.get("AWS_SECRET_ACCESS_KEY")
# EMAIL_BACKEND = "django_ses.SESBackend"
# AWS_SES_REGION_NAME = "us-east-1"
# AWS_SES_REGION_ENDPOINT = "email.us-east-1.amazonaws.com"
# USE_SES_V2 = True
# DEFAULT_FROM_EMAIL = SERVER_EMAIL = EMAIL_HOST_USER = env_config.get("EMAIL_HOST_USER")

# aws settings
# AWS_STORAGE_BUCKET_NAME = env_config.get("AWS_STORAGE_BUCKET_NAME")
# AWS_DEFAULT_ACL = None
# AWS_S3_SIGNATURE_VERSION = "s3v4"
# AWS_S3_REGION_NAME = "us-east-1"
# AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
# AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
# AWS_SQS_URL = env_config.get('AWS_SQS_URL')
# s3 static settings
STATIC_LOCATION = "static"
# STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/"
# STATICFILES_STORAGE = "core.storage_backends.StaticStorage"
# s3 public media settings
# PUBLIC_MEDIA_LOCATION = "media"
# MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/"
# DEFAULT_FILE_STORAGE = "core.storage_backends.PublicMediaStorage"
# s3 private media settings
# PRIVATE_MEDIA_LOCATION = "private"
# PRIVATE_FILE_STORAGE = "core.storage_backends.PrivateMediaStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL = "user.User"

REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.ScopedRateThrottle"],
    "EXCEPTION_HANDLER": "core.custom_middleware.custom_exception_handler",
    "COERCE_DECIMAL_TO_STRING": False,
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 900 * 1024 * 1024  # 500MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 900 * 1024 * 1024  # 500MB
FILE_UPLOAD_TIMEOUT = 900  # 15 minutes


CELERY_BROKER_URL = env_config.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = "America/New_York"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Redis cache toggle - set USE_REDIS_CACHE=False in dev.env to use local memory cache
USE_REDIS_CACHE = env_config.get("USE_REDIS_CACHE", default=True, cast=bool)

if USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CELERY_BROKER_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }


# =============================================================================
# JWT Settings (for wallet-based authentication)
# =============================================================================
JWT_SECRET_KEY = env_config.get(
    "JWT_SECRET_KEY", default="dev-jwt-secret-key-change-in-production"
)
JWT_EXPIRY_HOURS = env_config.get("JWT_EXPIRY_HOURS", default=24, cast=int)
JWT_ALGORITHM = "HS256"


# =============================================================================
# Web3 / Blockchain Settings
# =============================================================================
ETHEREUM_RPC_URL = env_config.get(
    "ETHEREUM_RPC_URL", default="https://eth.llamarpc.com"
)

# LI.FI API
LIFI_API_KEY = env_config.get("LIFI_API_KEY", default="")
LIFI_API_URL = "https://li.quest/v1"

# Agent Wallet (EOA that executes strategies)
AGENT_WALLET_ADDRESS = env_config.get("AGENT_WALLET_ADDRESS", default="")
# AGENT_WALLET_PRIVATE_KEY - only load when needed, not in settings

# Treasury (receives 10% performance fee)
TREASURY_ADDRESS = env_config.get("TREASURY_ADDRESS", default="")
