# Generated by Django 5.2.8 on 2026-02-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "address",
                    models.CharField(
                        help_text="Ethereum wallet address (0x...)",
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ens_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary ENS name for this wallet",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ens_min_apy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum APY preference (e.g., 5.00 for 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ens_max_risk",
                    models.CharField(
                        blank=True,
                        help_text="Maximum risk level: low, medium, high",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ens_chains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Allowed chains: ["base", "arbitrum", "avalanche"]',
                    ),
                ),
                (
                    "ens_protocols",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Allowed protocols: ["aave", "morpho", "euler"]',
                    ),
                ),
                (
                    "ens_auto_rebalance",
                    models.BooleanField(
                        default=False, help_text="Whether to auto-rebalance positions"
                    ),
                ),
                (
                    "ens_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time ENS preferences were fetched",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.CreateModel(
            name="AuthNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        help_text="Random nonce for SIWE message",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        help_text="Wallet address requesting authentication",
                        max_length=42,
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Nonce expiry time")),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether this nonce has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Auth Nonce",
                "verbose_name_plural": "Auth Nonces",
                "indexes": [
                    models.Index(
                        fields=["wallet_address", "nonce"],
                        name="wallets_aut_wallet__755c19_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="wallets_aut_expires_05d30e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_id",
                    models.IntegerField(
                        help_text="Chain ID (8453=Base, 42161=Arbitrum, 43114=Avalanche)"
                    ),
                ),
                (
                    "vault_address",
                    models.CharField(
                        help_text="Vault contract address on this chain", max_length=42
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this vault is active (false after cross-chain migration)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaults",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault",
                "verbose_name_plural": "Vaults",
                "unique_together": {("wallet", "chain_id", "vault_address")},
            },
        ),
    ]
