# Generated by Django 5.2.8 on 2026-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YieldPool",
            fields=[
                (
                    "pool_id",
                    models.CharField(
                        help_text="DeFiLlama pool ID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        help_text="Chain name (base, arbitrum, avalanche)",
                        max_length=50,
                    ),
                ),
                (
                    "chain_id",
                    models.IntegerField(help_text="Chain ID (8453, 42161, 43114)"),
                ),
                (
                    "project",
                    models.CharField(
                        help_text="Protocol name (aave-v3, morpho, euler)",
                        max_length=100,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Token symbol (e.g., USDC)", max_length=50
                    ),
                ),
                (
                    "tvl_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value locked in USD",
                        max_digits=20,
                    ),
                ),
                (
                    "apy",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Total APY (base + reward)",
                        max_digits=10,
                    ),
                ),
                (
                    "apy_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Base APY from lending",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "apy_reward",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Reward APY from incentives",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=5, help_text="Risk score 1-10 (1=lowest risk)"
                    ),
                ),
                (
                    "stable_coin",
                    models.BooleanField(
                        default=True, help_text="Whether this is a stablecoin pool"
                    ),
                ),
                (
                    "il_risk",
                    models.CharField(
                        default="none",
                        help_text="Impermanent loss risk (none, low, medium, high)",
                        max_length=20,
                    ),
                ),
                (
                    "pool_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional pool metadata from DeFiLlama",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Yield Pool",
                "verbose_name_plural": "Yield Pools",
                "ordering": ["-apy"],
                "indexes": [
                    models.Index(
                        fields=["chain", "project"], name="yields_yiel_chain_92754f_idx"
                    ),
                    models.Index(fields=["apy"], name="yields_yiel_apy_547835_idx"),
                    models.Index(
                        fields=["chain_id"], name="yields_yiel_chain_i_d11a15_idx"
                    ),
                    models.Index(
                        fields=["risk_score"], name="yields_yiel_risk_sc_7a9ce6_idx"
                    ),
                ],
            },
        ),
    ]
