# Generated by Django 5.2.8 on 2026-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yields", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yieldpool",
            name="contract_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Vault or deposit token address for LI.FI (e.g. aUSDC, Morpho vault, Euler vault)",
                max_length=42,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="yieldpool",
            name="chain",
            field=models.CharField(
                help_text="Chain name (base, arbitrum, optimism)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="yieldpool",
            name="chain_id",
            field=models.IntegerField(help_text="Chain ID (8453, 42161, 10)"),
        ),
        migrations.AlterField(
            model_name="yieldpool",
            name="project",
            field=models.CharField(
                help_text="Protocol name (aave-v3, morpho-v1, euler-v2)", max_length=100
            ),
        ),
    ]
