# Generated by Django 5.2.8 on 2026-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("event_path", models.CharField(max_length=150)),
                ("input", models.TextField()),
                ("output", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Parameters",
                "db_table": "parameters",
            },
        ),
    ]
