# Generated by Django 5.2.8 on 2026-02-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
        ("yields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_id",
                    models.IntegerField(help_text="Chain ID where position is held"),
                ),
                (
                    "protocol",
                    models.CharField(
                        help_text="Protocol name (aave-v3, morpho, euler)",
                        max_length=100,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token symbol (e.g., USDC)", max_length=50
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Amount in token's native decimals",
                        max_digits=30,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount in USD",
                        max_digits=20,
                    ),
                ),
                (
                    "current_apy",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Current APY for this position",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="wallets.vault",
                    ),
                ),
                (
                    "yield_pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="yields.yieldpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["-amount_usd"],
            },
        ),
        migrations.CreateModel(
            name="RebalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_chain_id", models.IntegerField(help_text="Source chain ID")),
                (
                    "from_protocol",
                    models.CharField(help_text="Source protocol name", max_length=100),
                ),
                (
                    "from_token",
                    models.CharField(help_text="Source token symbol", max_length=50),
                ),
                ("to_chain_id", models.IntegerField(help_text="Destination chain ID")),
                (
                    "to_protocol",
                    models.CharField(
                        help_text="Destination protocol name", max_length=100
                    ),
                ),
                (
                    "to_token",
                    models.CharField(
                        help_text="Destination token symbol", max_length=50
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Amount moved in token's native decimals",
                        max_digits=30,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount in USD at time of rebalance",
                        max_digits=20,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash (0x...)",
                        max_length=66,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "from_apy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="APY of source pool at time of rebalance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "to_apy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="APY of destination pool at time of rebalance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "apy_improvement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="APY improvement (to_apy - from_apy)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "agent_reasoning",
                    models.TextField(
                        blank=True,
                        help_text="Why AI decided to make this rebalance",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the rebalance completed", null=True
                    ),
                ),
                (
                    "from_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rebalances_from",
                        to="wallets.vault",
                    ),
                ),
                (
                    "to_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rebalances_to",
                        to="wallets.vault",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_history",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rebalance History",
                "verbose_name_plural": "Rebalance History",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="positions_r_wallet__5f4ccf_idx",
                    ),
                    models.Index(
                        fields=["status"], name="positions_r_status_b543d1_idx"
                    ),
                    models.Index(
                        fields=["tx_hash"], name="positions_r_tx_hash_6acc41_idx"
                    ),
                ],
            },
        ),
    ]
