# Generated by Django 5.2.8 on 2026-02-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="protocol",
            field=models.CharField(
                help_text="Protocol name (aave-v3, morpho-v1, euler-v2)", max_length=100
            ),
        ),
    ]
